apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/bound-by-controller: "yes"
  creationTimestamp: null
  labels:
    volume: pv0001
  name: pv0001
spec:
  accessModes:
  - ReadWriteOnce
  - ReadWriteMany
  - ReadOnlyMany
  capacity:
    storage: 100Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: pv0001
#    namespace: gravitee
#    resourceVersion: "19730"
#    uid: 0a51059a-10b4-11e8-8c1c-bed6e11feb98
  hostPath:
    path: /var/lib/minishift/openshift.local.pv/pv0001
  persistentVolumeReclaimPolicy: Recycle
#status: {}
